-- FIXED SUPABASE MIGRATION SCRIPT: ujgnfwdeifiqvvvbeyjk -> acyqrpkdsxddkqfaakty
-- Generated by Antigravity (Corrected)

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. ENUMS (Ensuring all are present)
DO $$ BEGIN
    CREATE TYPE public.billing_status AS ENUM ('pending', 'paid', 'overdue', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.billing_type AS ENUM ('subscription', 'credit_purchase', 'system_usage', 'adjustment');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE public.crm_status AS ENUM ('novo', 'negociacao', 'followup', 'fechado', 'perdido');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- (Assuming other enums are correct or will fail gracefully if missing - focusing on core table columns first)

-- 3. TABLES (Updating with missing columns found via information_schema)

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL,
    nome TEXT,
    telefone TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'user', -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    nome TEXT NOT NULL,
    slug TEXT UNIQUE,
    plan TEXT DEFAULT 'free',
    saldo_bonus DECIMAL(10,2) DEFAULT 0,
    saldo_sacavel DECIMAL(10,2) DEFAULT 0,
    acesso_crm BOOLEAN DEFAULT false, -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_organizations (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, organization_id)
);

CREATE TABLE IF NOT EXISTS public.planos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    nome TEXT NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    limite_clientes INTEGER,
    organization_id UUID REFERENCES public.organizations(id),
    acesso_crm BOOLEAN DEFAULT false, -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.servicos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    nome TEXT NOT NULL,
    preco DECIMAL(10,2),
    organization_id UUID REFERENCES public.organizations(id),
    ativo BOOLEAN DEFAULT true, -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.clientes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES public.organizations(id),
    tipo_pessoa TEXT NOT NULL DEFAULT 'fisica',
    nome_completo TEXT NOT NULL,
    email TEXT NOT NULL,
    celular TEXT NOT NULL,
    cpf TEXT,
    cnpj TEXT,
    endereco JSONB,
    ativo BOOLEAN DEFAULT true, -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.veiculos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE,
    placa TEXT NOT NULL,
    modelo TEXT NOT NULL,
    ano TEXT,
    renavam TEXT,
    ativo BOOLEAN DEFAULT true, -- MISSING
    rastreamento_ativo BOOLEAN DEFAULT false, -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.multas (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    veiculo_id UUID REFERENCES public.veiculos(id) ON DELETE CASCADE,
    codigo_infracao TEXT,
    descricao TEXT,
    status TEXT DEFAULT 'pendente',
    valor DECIMAL(10,2),
    data_multa DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.contratos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE,
    servico_id UUID REFERENCES public.servicos(id),
    organization_id UUID REFERENCES public.organizations(id),
    status TEXT DEFAULT 'pendente',
    valor DECIMAL(10,2),
    alerta_ativo BOOLEAN DEFAULT false, -- MISSING
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.historico_atividades (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES public.organizations(id),
    tipo TEXT,
    descricao TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: In the donor, 'documentos' table seems to exist separately from the storage bucket
CREATE TABLE IF NOT EXISTS public.documentos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE,
    tipo TEXT,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
