project_id = "acyqrpkdsxddkqfaakty"

[functions.generate-recurso]
verify_jwt = false

[functions.consultar-veiculo]
verify_jwt = false

[functions.certadoc]
verify_jwt = false

[functions.rastreamento-semanal]
verify_jwt = false

[functions.extrair-ait]
verify_jwt = false

[functions.analisar-documento-conhecimento]
verify_jwt = false

[functions.cancelar-rastreamento]
verify_jwt = false

[functions.verificar-vencimento-rastreamento]
verify_jwt = false

[functions.listar-placas-consultadas]
verify_jwt = false

[functions.registrar-notificacao]
verify_jwt = false

[functions.enviar-email]
verify_jwt = false

[functions.infinitepay-checkout]
verify_jwt = false
